# Generated by Django 5.2.1 on 2025-06-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_enrollment_class_type_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('evening', 'Evening / After-School Class'), ('weekend', 'Weekend Class'), ('holiday', 'Holiday / Summer Class')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('schedule_days', models.CharField(max_length=100)),
                ('time_slots', models.TextField(help_text='Separate multiple time slots with commas.')),
                ('fee_per_session', models.CharField(max_length=50)),
                ('fee_for_bundle', models.CharField(max_length=50)),
                ('class_size', models.PositiveIntegerField()),
                ('discount_siblings', models.BooleanField(default=True)),
                ('discount_early', models.BooleanField(default=True)),
                ('discount_group', models.BooleanField(default=True)),
            ],
        ),
    ]
