# Generated by Django 5.2.1 on 2025-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_enrollment_is_paid_enrollment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_course_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_enrollment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='login_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use placeholders like {{ name }}, {{ email }}, etc., in your template body'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
