# Generated by Django 5.2.1 on 2025-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='session_option',
            field=models.CharField(choices=[('session', 'One Session'), ('multiple', 'Multiple Sessions'), ('bundle', 'Bundle (10 Sessions)')], default='session', max_length=20),
        ),
    ]
