# Generated by Django 5.2.1 on 2025-08-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_parenttestimonial_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='remark',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='correction_file',
            field=models.FileField(blank=True, help_text='Optional: Upload corrected file for student to download', null=True, upload_to='assignments/corrections/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback_comments',
            field=models.TextField(blank=True, help_text='Optional: Write grading feedback', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='assignments/submissions/'),
        ),
    ]
