# Generated by Django 5.2.1 on 2025-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_courseplan_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_activation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
