# Generated by Django 5.2.1 on 2025-09-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_enrollment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='has_changed_password',
            new_name='has_set_password',
        ),
    ]
