# Generated by Django 5.2.1 on 2025-10-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_enrollment_is_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='dashboard_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
