# Generated by Django 5.2.1 on 2025-10-27 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_assignment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
