# Generated by Django 5.2.1 on 2025-11-01 02:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_material_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltimetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='globaltimetable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 2, 26, 39, 629384, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
