# Generated by Django 5.2.1 on 2025-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_livesession_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('App Inventor', 'App Inventor'), ('Advance Full Stack Web Development with Django', 'Advance Full Stack Web Development with Django'), ('Robotics with Arduino Uno and Micro:bit', 'Robotics with Arduino Uno and Micro:bit'), ('Python Programming', 'Python Programming'), ('Full Stack Web Dev (Django)', 'Full Stack Web Dev (Django)'), ('Scratch and PictoBlox Coding', 'Scratch and PictoBlox Coding'), ('Frontend Web Development (HTML, CSS & JavaScript)', 'Frontend Web Development (HTML, CSS & JavaScript)'), ('Responsive Web Development with Bootstrap 5', 'Responsive Web Development with Bootstrap 5'), ('Full Stack Web Development with Laravel', 'Full Stack Web Development with Laravel')], max_length=100),
        ),
    ]
