# Generated by Django 5.2.1 on 2025-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_enrollment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
                ('who_we_are', models.TextField()),
                ('what_we_do', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Enter features separated by line breaks.')),
                ('mode_of_delivery', models.CharField(max_length=300)),
                ('class_size', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order programs appear on the page')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro1', models.TextField(verbose_name='First Paragraph')),
                ('intro2', models.TextField(verbose_name='Second Paragraph')),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('App Inventor', 'App Inventor'), ('Advance Full Stack Web Development with Django', 'Advance Full Stack Web Development with Django'), ('Robotics with Arduino Uno and Micro:bit', 'Robotics with Arduino Uno and Micro:bit'), ('Python Programming', 'Python Programming'), ('Full Stack Web Development with Django', 'Full Stack Web Development with Django'), ('Scratch and PictoBlox Coding', 'Scratch and PictoBlox Coding'), ('Frontend Web Development (HTML, CSS & JavaScript)', 'Frontend Web Development (HTML, CSS & JavaScript)'), ('Responsive Web Development with Bootstrap 5', 'Responsive Web Development with Bootstrap 5'), ('Full Stack Web Development with Laravel', 'Full Stack Web Development with Laravel')], max_length=100),
        ),
    ]
