# Generated by Django 5.2.1 on 2025-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_course_options_remove_course_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
