# Generated by Django 5.2.1 on 2025-12-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
