# Generated by Django 5.2.1 on 2025-12-27 13:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bankdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='brochure',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='services/brochures/'),
        ),
    ]
