# Generated by Django 5.2.1 on 2025-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
