# Generated by Django 5.2.1 on 2025-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('program', models.CharField(choices=[('in_person', 'In-person'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20)),
                ('course', models.CharField(choices=[('begin_scratch', 'Beginning Scratch Coding'), ('inter_scratch', 'Intermediate Scratch Coding'), ('begin_python', 'Beginning Python Coding'), ('inter_python', 'Intermediate Python Coding'), ('web_html_css', 'Web Development (HTML & CSS)'), ('web_bootstrap', 'Web Development (Frontend) with Bootstrap 5'), ('full_laravel', 'Full Stack using Laravel'), ('full_django', 'Full Stack using Django'), ('robot_arduino', 'Robotics with Arduino Uno'), ('robot_microbits', 'Robotics with Microbits'), ('app_inventor', 'App Inventor')], max_length=30)),
                ('class_type', models.CharField(choices=[('evening', 'Evening / After School class'), ('weekend', 'Weekend class'), ('holiday', 'Holiday / Summer class'), ('special', 'Special class')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
