# Generated by Django 5.2.1 on 2025-06-02 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('begin_scratch', 'Beginner / Intermediate Scratch Coding'), ('inter_scratch', 'Intermediate Scratch Coding'), ('begin_python', 'Beginner Python Coding'), ('inter_python', 'Intermediate / Advance Python Coding'), ('web_html_css', 'Web Development (HTML & CSS)'), ('web_bootstrap', 'Web Development (Frontend) with Bootstrap 5'), ('full_laravel', 'Full Stack using Laravel'), ('full_django', 'Full Stack using Django'), ('robot_arduino', 'Robotics with Arduino Uno'), ('robot_microbits', 'Robotics with Microbits'), ('app_inventor', 'App Inventor')], max_length=30),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
