# Generated by Django 5.2.1 on 2025-06-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_type',
            field=models.CharField(choices=[('evening', 'Evening / After School Class'), ('weekend', 'Weekend Class'), ('holiday', 'Holiday / Summer Class'), ('special', 'Special Class')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('begin_scratch', 'Beginner / Intermediate Scratch Coding'), ('inter_scratch', 'Intermediate Scratch Coding'), ('begin_python', 'Beginner Python Coding'), ('inter_python', 'Intermediate / Advanced Python Coding'), ('web_html_css', 'Web Development (HTML & CSS)'), ('web_bootstrap', 'Web Development (Frontend with Bootstrap 5)'), ('full_laravel', 'Full Stack using Laravel'), ('full_django', 'Full Stack using Django'), ('robot_arduino', 'Robotics with Arduino Uno'), ('robot_microbits', 'Robotics with Micro:bit'), ('app_inventor', 'App Inventor')], max_length=30),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.course')),
            ],
        ),
    ]
