# Generated by Django 5.2.1 on 2025-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_courseplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for this template (e.g. contact_auto_reply)', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Subject line of the email', max_length=255)),
                ('body', models.TextField(help_text='Use {{ name }}, {{ email }}, {{ subject }}, and {{ message }} as placeholders')),
            ],
        ),
    ]
