# Generated by Django 5.2.1 on 2025-06-15 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_type',
            field=models.CharField(choices=[('Evening / After-School Class', 'Evening / After-School Class'), ('Weekend Class', 'Weekend Class'), ('Holiday / Summer Class', 'Holiday / Summer Class')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('App Inventor', 'App Inventor'), ('Robotics with Micro:bit', 'Robotics with Micro:bit'), ('Robotics with Arduino Uno', 'Robotics with Arduino Uno'), ('Python Programming', 'Python Programming'), ('Full Stack Web Dev (Django)', 'Full Stack Web Dev (Django)'), ('Scratch and PictoBlox Coding', 'Scratch and PictoBlox Coding'), ('Frontend Web Development', 'Frontend Web Development'), ('Responsive Design with Bootstrap 5', 'Responsive Design with Bootstrap 5'), ('Full Stack Development with Laravel', 'Full Stack Development with Laravel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='program',
            field=models.CharField(choices=[('In-person Program', 'In-person Program'), ('Online Program', 'Online Program'), ('Hybrid Program', 'Hybrid Program')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
