# Generated by Django 5.2.1 on 2025-06-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_enrollment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('part', 'Part Payment')], max_length=10)),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('bank', 'Bank Transfer')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.enrollment')),
            ],
        ),
    ]
