# Generated by Django 5.2.1 on 2025-07-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
