# Generated by Django 5.2.1 on 2025-07-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_parenttestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenttestimonial',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
