# Generated by Django 5.2.1 on 2025-08-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='login_code',
        ),
    ]
