# Generated by Django 5.2.1 on 2025-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_enrollment_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='class_type',
            field=models.CharField(choices=[('evening', 'Evening / After-School Class'), ('weekend', 'Weekend Class'), ('holiday', 'Holiday / Summer Class'), ('special', 'Special Class')], max_length=20, unique=True),
        ),
    ]
