# Generated by Django 5.2.1 on 2025-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_enrollment_is_activation_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(choices=[('App Inventor', 'App Inventor'), ('Robotics with Micro:bit', 'Robotics with Micro:bit'), ('Robotics with Arduino Uno', 'Robotics with Arduino Uno'), ('Python Programming', 'Python Programming'), ('Full Stack Web Dev (Django)', 'Full Stack Web Dev (Django)'), ('Scratch and PictoBlox Coding', 'Scratch and PictoBlox Coding'), ('Frontend Web Development (HTML, CSS & JavaScript)', 'Frontend Web Development (HTML, CSS & JavaScript)'), ('Responsive Web Development with Bootstrap 5', 'Responsive Web Development with Bootstrap 5'), ('Full Stack Development with Laravel', 'Full Stack Development with Laravel')], max_length=100),
        ),
    ]
