# Generated by Django 5.2.1 on 2025-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_has_changed_password_enrollment_has_set_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_temp_password',
            field=models.BooleanField(default=True),
        ),
    ]
