# Generated by Django 5.2.1 on 2025-10-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_material_recipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
