# Generated by Django 5.2.1 on 2025-12-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_delete_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
            preserve_default=False,
        ),
    ]
