# Generated by Django 5.2.1 on 2025-12-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='amount_paid',
            new_name='amount_due',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New Request'), ('approved', 'Approved – Awaiting Payment'), ('paid', 'Paid')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paystack', 'Paystack'), ('bank', 'Bank Transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.servicerequest')),
            ],
        ),
    ]
